_wandb:
    value:
        cli_version: 0.25.1
        e:
            9ktn9k9h3ulwjdvj8c6g169n7c8x5y4t:
                codePath: /cephyr/users/vollmers/Alvis/vollmers/gnn-thesis/gnn-thesis/notebooks/02_model_training.ipynb
                codePathLocal: 02_model_training.ipynb
                cpu_count: 16
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "18843648000"
                        used: "10686177280"
                email: elonvginstrup@gmail.com
                executable: /cephyr/users/vollmers/Alvis/vollmers/gnn-thesis/bin/python
                git:
                    commit: 8f923f6d9981993cc87abd56afb49b6b1b85caa4
                    remote: https://github.com/elonvg/gnn-thesis.git
                gpu: Tesla V100-SXM2-32GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-d8341780-5812-1938-73ee-7397bcf53600
                host: alvis1-09
                memory:
                    total: "809682460672"
                os: Linux-4.18.0-553.109.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /cephyr/users/vollmers/Alvis/vollmers/gnn-thesis/gnn-thesis/notebooks/02_model_training.ipynb
                python: CPython 3.11.3
                root: /cephyr/users/vollmers/Alvis/vollmers/gnn-thesis/gnn-thesis/notebooks
                slurm:
                    cluster_name: alvis
                    conf: /tmp/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "8"
                    export_env: NONE
                    get_user_env: "1"
                    gpus_on_node: "1"
                    gpus_per_node: V100:1
                    gtids: "0"
                    job_account: naiss2025-5-534
                    job_cpus_per_node: "8"
                    job_end_time: "1777659076"
                    job_gid: "10069639"
                    job_gpus: "1"
                    job_id: "6556043"
                    job_name: sys/dashboard/sys/bc_alvis_codeserver
                    job_nodelist: alvis1-09
                    job_num_nodes: "1"
                    job_partition: alvis
                    job_qos: normal
                    job_start_time: "1777644675"
                    job_uid: "10069639"
                    job_user: vollmers
                    jobid: "6556043"
                    localid: "0"
                    mem_per_node: "191520"
                    mpi_type: pmix
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: alvis1-09
                    oom_kill_step: "0"
                    pmix_direct_conn_ucx: "false"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /var/www/ood/apps/sys/dashboard
                    submit_host: roberto
                    task_pid: "37736"
                    tasks_per_node: "1"
                    topology_addr: ib-root.ib-sw01.alvis1-09
                    topology_addr_pattern: switch.switch.node
                startedAt: "2026-05-01T14:39:05.655873Z"
                writerId: 9ktn9k9h3ulwjdvj8c6g169n7c8x5y4t
        m:
            - "1": epoch
              "6":
                - 3
              "7": []
            - "2": optimizer/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": train/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": val/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": test/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.3
        t:
            "1":
                - 1
                - 5
                - 53
                - 77
            "2":
                - 1
                - 5
                - 53
                - 77
            "3":
                - 2
                - 7
                - 15
                - 16
                - 62
            "4": 3.11.3
            "5": 0.25.1
            "8":
                - 1
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 512
butina_cluster_col:
    value: Cluster_at_cutoff_0.2
categorical_cols:
    value:
        - species_group
        - conc_unit
        - endpoint
        - effect
        - is_salt
        - has_metal
        - is_single_node
categorical_dim:
    value: 16
dropout:
    value: 0.3
duration_fill_value:
    value: 1e-06
early_stopping_min_delta:
    value: 0.0001
early_stopping_patience:
    value: 30
filters:
    value:
        duration_unit:
            - h
        effect:
            - MOR
            - POP
            - GRO
            - BEH
            - REP
            - ITX
            - PHY
            - DVP
            - MPH
final_hidden_dim:
    value: 64
frac_test:
    value: 0.2
frac_train:
    value: 0.7
frac_valid:
    value: 0.1
gnn_hidden_dim:
    value: 64
gnn_model:
    value: AFPFlex
gnn_out_dim:
    value: 64
learning_rate:
    value: 0.0003
log_transform_duration:
    value: true
loss:
    value: SmoothL1Loss
loss_beta:
    value: 0.5
max_conc_value:
    value: 10000
max_duration_hours:
    value: 9000
meta_dropout:
    value: 0.3
n_params_gnn:
    value: 130112
n_params_meta:
    value: 691472
n_params_total:
    value: 836177
n_samples:
    value: null
num_atom_features:
    value: 7
num_bond_features:
    value: 3
num_layers:
    value: 3
num_timesteps:
    value: 2
numeric_dim:
    value: 16
numerical_cols:
    value:
        - duration
        - fragment_count
pretrained_tax_dim:
    value: 768
pretrained_taxid_output_dim:
    value: 128
random_state:
    value: 11
remove_lone:
    value: false
remove_metals:
    value: false
split_method:
    value: butina
split_salt:
    value: false
stratify_by:
    value:
        - species_group
        - endpoint
        - effect
        - conc_unit
tax_dim:
    value: 16
tax_embedding:
    value:
        taxid: 16
taxonomy_encoder:
    value: TaxonomyOneHot
use_pretrained_taxid:
    value: true
weight_decay:
    value: 0.0001
